/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface BjeckMainNavbar {

    }
  }

  interface HTMLBjeckMainNavbarElement extends StencilComponents.BjeckMainNavbar, HTMLStencilElement {}

  var HTMLBjeckMainNavbarElement: {
    prototype: HTMLBjeckMainNavbarElement;
    new (): HTMLBjeckMainNavbarElement;
  };
  interface HTMLElementTagNameMap {
    'bjeck-main-navbar': HTMLBjeckMainNavbarElement;
  }
  interface ElementTagNameMap {
    'bjeck-main-navbar': HTMLBjeckMainNavbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bjeck-main-navbar': JSXElements.BjeckMainNavbarAttributes;
    }
  }
  namespace JSXElements {
    export interface BjeckMainNavbarAttributes extends HTMLAttributes {
      'onOpenBtn'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface BjeckSideNavbar {

    }
  }

  interface HTMLBjeckSideNavbarElement extends StencilComponents.BjeckSideNavbar, HTMLStencilElement {}

  var HTMLBjeckSideNavbarElement: {
    prototype: HTMLBjeckSideNavbarElement;
    new (): HTMLBjeckSideNavbarElement;
  };
  interface HTMLElementTagNameMap {
    'bjeck-side-navbar': HTMLBjeckSideNavbarElement;
  }
  interface ElementTagNameMap {
    'bjeck-side-navbar': HTMLBjeckSideNavbarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bjeck-side-navbar': JSXElements.BjeckSideNavbarAttributes;
    }
  }
  namespace JSXElements {
    export interface BjeckSideNavbarAttributes extends HTMLAttributes {
      'onCloseBtn'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface BjeckSidemenuBundle {

    }
  }

  interface HTMLBjeckSidemenuBundleElement extends StencilComponents.BjeckSidemenuBundle, HTMLStencilElement {}

  var HTMLBjeckSidemenuBundleElement: {
    prototype: HTMLBjeckSidemenuBundleElement;
    new (): HTMLBjeckSidemenuBundleElement;
  };
  interface HTMLElementTagNameMap {
    'bjeck-sidemenu-bundle': HTMLBjeckSidemenuBundleElement;
  }
  interface ElementTagNameMap {
    'bjeck-sidemenu-bundle': HTMLBjeckSidemenuBundleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'bjeck-sidemenu-bundle': JSXElements.BjeckSidemenuBundleAttributes;
    }
  }
  namespace JSXElements {
    export interface BjeckSidemenuBundleAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
